---
title: "STATISTICS 2023-2024"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      primary: "#77253D"
      bootswatch: default
    orientation: rows
    vertical_layout: scroll
    logo: www/logo-nba.svg
---

```{r setup, include=FALSE}
# Packages
library(dplyr)
library(readr)
library(shiny)
library(htmltools)
library(flexdashboard)
library(ggplot2)
library(gt)
library(DT)

# Load data
season_23_24 <- read_csv("Data/2023-24.csv")
```


Sidebar {.sidebar}
=======================================================================
```{r}
selectInput("teams",
            "SELECT A TEAM",
            choices = sort(unique(season_23_24$TEAM_ABBREVIATION)),
            selected = "ATL")

selectInput("players",
            "SELECT A PLAYER",
            choices = NULL)

# Placeholder for dynamic image output
# uiOutput("team_logo")

# Observe selection on Team input
observe({
  team_selected <- input$teams
    
  # Check if team_selected is NULL or empty, return early if it is
  if (is.null(team_selected) || team_selected == "") {
    return()
  }
  
  players_list <- season_23_24 %>% 
    filter(TEAM_ABBREVIATION == team_selected) %>% 
    select(PLAYER_NAME)
  
  players_list <-  sort(unique(players_list$PLAYER_NAME))
  
  # Update the Players based on the team selected,
  # setting the choices to the relevant subset from the players list
  updateSelectInput(session, 
                    "players",
                    label = "SELECT A PLAYER",
                    choices = players_list,
                    selected = players_list[1])
})

roster <- reactive({
  season_23_24 %>% filter(TEAM_ABBREVIATION == input$teams)
})

current <- reactive({
  season_23_24 %>% filter(PLAYER_NAME == input$players)
})


# output$team_logo <- renderUI({
#   # Obtain the selected team name
#   selected_team <- tolower(input$teams)
# 
#   # If a team is selected, show its logo
#   if (!is.null(selected_team)) {
#     img_src <- paste0("www/logo-", selected_team, ".svg")
#     print(img_src)
#     tags$img(src = img_src, height = "auto", width = "auto")
#   }
# })

create_stat_plot <- function(stat) {
  df <- reactive({
    roster() %>% 
      mutate(PlayerSelected = if_else(PLAYER_NAME == input$players, 
                                      "Selected", "Not Selected"),
             stats = .data[[stat]]) %>%
      arrange(desc(stats)) %>% 
      mutate(PLAYER_NAME = factor(PLAYER_NAME, levels = PLAYER_NAME))
  })
  
  
  ggplot(df(), aes_string(x = "PLAYER_NAME", y = stat, fill = "PlayerSelected")) +
    geom_bar(stat = "identity", alpha = .6, width = .5, show.legend = F) +
    scale_fill_manual(values = c("Selected" = "#6F263D", "Not Selected" = "#1d428a")) +
    coord_flip() +
    xlab("") +
    theme_minimal() 
}

create_top_10 <- function(stat) {
  df <- reactive({
    season_23_24 %>% 
      mutate(PlayerSelected = if_else(PLAYER_NAME == input$players, 
                                      "Selected", "Not Selected"),
             stats = .data[[stat]]) %>%
      arrange(desc(stats)) %>% 
      mutate(PLAYER_NAME = factor(PLAYER_NAME, levels = PLAYER_NAME)) %>% 
      slice_head(n = 10)
  })
  
  
  ggplot(df(), aes_string(x = "PLAYER_NAME", y = stat, fill = "PlayerSelected")) +
    geom_bar(stat = "identity", alpha = .6, width = .5, show.legend = F) +
    scale_fill_manual(values = c("Selected" = "#6F263D", "Not Selected" = "#1d428a")) +
    coord_flip() +
    xlab("") +
    theme_minimal() 
}
```

SUMMARY 
=======================================================================

Row
-----------------------------------------------------------------------

### Team 
```{r}
renderValueBox({
  valueBox(
    value = current()$TEAM_ABBREVIATION,
    caption = "Team",
    icon = "fa-shirt",
    color = "#1d428a"
  )
})
```


### Age 
```{r}
renderValueBox({
  valueBox(
    value = current()$AGE,
    caption = "Years old",
    icon = "fa-calendar",
    color = "#1d428a"
  )
})
```


### Minutes per Game 
```{r}
renderValueBox({
  valueBox(
    value = current()$MIN,
    caption = "Minutes Per Game",
    icon = "fa-clock",
    color = "#1d428a"
  )
})
```


### Games Played
```{r}
renderValueBox({
  valueBox(
    value = current()$GP,
    caption = "Games Played",
    icon = "fa-calendar-check",
    color = "#1d428a"
  )
})
```


### Points per Game 
```{r}
renderValueBox({
  valueBox(
    value = current()$PTS,
    caption = "Points Per Game",
    icon = "fa-basketball",
    color = "#1d428a"
  )
})
```


Row
-----------------------------------------------------------------------

### Field Goal Percentage
```{r}
renderGauge({
  gauge(value = 100 * current()$FG_PCT,
      min = 0,
      max = 100,
      symbol = '%', 
      gaugeSectors(success = c(40, 100), warning = c(20, 40), danger = c(0, 20),
                   colors = c("#0c4e24", "#FDBB30", "#ce1141"))
  )
})
```


### Free Throw Percentage
```{r}
renderGauge({
  gauge(value = 100 * current()$FT_PCT,
      min = 0,
      max = 100,
      symbol = '%', 
      gaugeSectors(success = c(75, 100), warning = c(60, 75), danger = c(0, 60),
                   colors = c("#0c4e24", "#FDBB30", "#ce1141"))
  )
})
```


### 3 Point Percentage
```{r}
renderGauge({
  gauge(value = 100 * current()$FG3_PCT,
      min = 0,
      max = 100,
      symbol = '%', 
      gaugeSectors(success = c(35, 100), warning = c(20, 35), danger = c(0, 20),
                   colors = c("#0c4e24", "#FDBB30", "#ce1141"))
  )
})
```


Row
-----------------------------------------------------------------------

### Assists per Game 
```{r}
renderValueBox({
  valueBox(
    value = current()$AST,
    caption = "Assists Per Game",
    icon = "fa-handshake-angle",
    color = "#1d428a"
  )
})
```


### Rebounds per Game 
```{r}
renderValueBox({
  valueBox(
    value = current()$REB,
    caption = "Rebounds Per Game",
    icon = "fa-hands-holding-circle",
    color = "#1d428a"
  )
})
```


### Blocks per Game
```{r}
renderValueBox({
  valueBox(
    value = current()$BLK,
    caption = "Blocks Per Game",
    icon = "fa-hand-point-up",
    color = "#1d428a"
  )
})
```


### Steals per Game
```{r}
renderValueBox({
  valueBox(
    value = current()$STL,
    caption = "Steals Per Game",
    icon = "fa-people-robbery",
    color = "#1d428a"
  )
})
```


### Turnovers per Game
```{r}
renderValueBox({
  valueBox(
    value = current()$TOV,
    caption = "Turnovers Per Game",
    icon = "fa-person-walking-arrow-loop-left",
    color = "#1d428a"
  )
})
```

Row {.tabset}
-----------------------------------------------------------------------

### Points Comparison
```{r}
renderPlot({
  create_stat_plot("PTS")
})
```


### Assists Comparison
```{r}
renderPlot({
  create_stat_plot("AST")
})
```


### Rebounds Comparison
```{r}
renderPlot({
  create_stat_plot("REB")
})
```


OFFENSE {data-navmenu="Under Development"}
=======================================================================

This tab is currently under development. Stay tuned!

Row
-----------------------------------------------------------------------

<!-- ### Minutes per Game  -->
<!-- ```{r} -->
<!-- renderValueBox({ -->
<!--   valueBox( -->
<!--     value = current()$MIN, -->
<!--     caption = "Minutes Per Game", -->
<!--     icon = "fa-clock", -->
<!--     color = "#1d428a" -->
<!--   ) -->
<!-- }) -->
<!-- ``` -->


<!-- ### Points per Game  -->
<!-- ```{r} -->
<!-- renderValueBox({ -->
<!--   valueBox( -->
<!--     value = current()$PTS, -->
<!--     caption = "Points Per Game", -->
<!--     icon = "fa-basketball", -->
<!--     color = "#1d428a" -->
<!--   ) -->
<!-- }) -->
<!-- ``` -->


<!-- ### Field Goal Attempted per Game  -->
<!-- ```{r} -->
<!-- renderValueBox({ -->
<!--   valueBox( -->
<!--     value = current()$FGA, -->
<!--     caption = "FG Attempted Per Game", -->
<!--     icon = "fa-dribbble", -->
<!--     color = "#1d428a" -->
<!--   ) -->
<!-- }) -->
<!-- ``` -->


<!-- ### 3 Points Attempted per Game  -->
<!-- ```{r} -->
<!-- renderValueBox({ -->
<!--   valueBox( -->
<!--     value = current()$FG3A, -->
<!--     caption = "3 Pts Attempted Per Game", -->
<!--     icon = "fa-hands-asl-interpreting", -->
<!--     color = "#1d428a" -->
<!--   ) -->
<!-- }) -->
<!-- ``` -->


<!-- ### Free Throws Attempted per Game  -->
<!-- ```{r} -->
<!-- renderValueBox({ -->
<!--   valueBox( -->
<!--     value = current()$FTA, -->
<!--     caption = "FT Attempted Per Game", -->
<!--     icon = "fa-ring", -->
<!--     color = "#1d428a" -->
<!--   ) -->
<!-- }) -->
<!-- ``` -->


DEFENSE {data-navmenu="Under Development"}
=======================================================================

This tab is currently under development. Stay tuned!

Row
-----------------------------------------------------------------------

LEADERS
=======================================================================

Row {.tabset}
-----------------------------------------------------------------------

### Points
```{r}
renderPlot({
  create_top_10("PTS")
})
```


### Assists
```{r}
renderPlot({
  create_top_10("AST")
})
```


### Turnovers
```{r}
renderPlot({
  create_top_10("TOV")
})
```


### Rebounds
```{r}
renderPlot({
  create_top_10("REB")
})
```


### Blocks
```{r}
renderPlot({
  create_top_10("BLK")
})
```


### Steals
```{r}
renderPlot({
  create_top_10("STL")
})
```


Row
-----------------------------------------------------------------------
### Western Ranking
### Eastern Ranking

TEAM ABBREVIATION
=======================================================================

Row {data-height=550}
-----------------------------------------------------------------------

### FRANCHISES
```{r}
rosters <- season_23_24 %>% 
  select(TEAM_ABBREVIATION) %>% 
  unique() %>% 
  arrange(TEAM_ABBREVIATION) %>% 
  mutate(FULL_NAME = case_when(
    TEAM_ABBREVIATION == "ATL" ~ "ATLANTA HAWKS",
    TEAM_ABBREVIATION == "BKN" ~ "BROOKLYN NETS",
    TEAM_ABBREVIATION == "BOS" ~ "BOSTON CELTICS",
    TEAM_ABBREVIATION == "CHA" ~ "CHARLOTTE HORNETS",
    TEAM_ABBREVIATION == "CHI" ~ "CHICAGO BULLS",
    TEAM_ABBREVIATION == "CLE" ~ "CLEVELAND CAVALIERS",
    TEAM_ABBREVIATION == "DAL" ~ "DALLAS MAVERICKS",
    TEAM_ABBREVIATION == "DEN" ~ "DENVER NUGGETS",
    TEAM_ABBREVIATION == "DET" ~ "DETROIT PISTONS",
    TEAM_ABBREVIATION == "GSW" ~ "GOLDEN STATE WARRIORS",
    TEAM_ABBREVIATION == "HOU" ~ "HOUSTON ROCKETS",
    TEAM_ABBREVIATION == "IND" ~ "INDIANA PACERS",
    TEAM_ABBREVIATION == "LAC" ~ "LOS ANGELES CLIPPERS",
    TEAM_ABBREVIATION == "LAL" ~ "LOS ANGELES LAKERS",
    TEAM_ABBREVIATION == "MEM" ~ "MEMPHIS GRIZZLIES",
    TEAM_ABBREVIATION == "MIA" ~ "MIAMI HEAT",
    TEAM_ABBREVIATION == "MIL" ~ "MILWAUKEE BUCKS",
    TEAM_ABBREVIATION == "MIN" ~ "MINNESOTA TIMBERWOLVES",
    TEAM_ABBREVIATION == "NOP" ~ "NEW ORLEANS PELICANS",
    TEAM_ABBREVIATION == "NYK" ~ "NEW YORK KNICKS",
    TEAM_ABBREVIATION == "OKC" ~ "OKLAHOMA CITY THUNDER",
    TEAM_ABBREVIATION == "ORL" ~ "ORLANDO MAGIC",
    TEAM_ABBREVIATION == "PHI" ~ "PHILADELPHIA SEVENTY SIXERS",
    TEAM_ABBREVIATION == "PHX" ~ "PHOENIX SUNS",
    TEAM_ABBREVIATION == "POR" ~ "PORTLAND TRAIL BLAZZERS",
    TEAM_ABBREVIATION == "SAC" ~ "SACRAMENTO KINGS",
    TEAM_ABBREVIATION == "SAS" ~ "SAN ANTONIO SPURS",
    TEAM_ABBREVIATION == "TOR" ~ "TORONTO RAPTORS",
    TEAM_ABBREVIATION == "UTA" ~ "UTAH JAZZ",
    TEAM_ABBREVIATION == "WAS" ~ "WASHINGTON WIZZARDS"
  ))

render_gt({
  rosters %>% 
    gt() %>% 
    tab_header(title = md(paste0(fontawesome::fa("basketball"), 
                                 "   **NBA FRANCHISES: LOVE THEM OR HATE THEM**   ",
                                 fontawesome::fa("basketball"))),
               # subtitle = md("*Low them or hate them*")
               ) %>% 
    cols_align(align = "right",
               columns = FULL_NAME) %>% 
    cols_label(TEAM_ABBREVIATION = md("**Team Abbreviation**"),
               FULL_NAME = md("**Team Full Name**")) %>% 
    opt_interactive(use_compact_mode = T)
})
```


<!-- ### TABLE 2 -->
<!-- ```{r} -->
<!-- renderDT({ -->
<!--   rosters %>% -->
<!--     datatable() -->
<!-- }) -->
<!-- ``` -->

